//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accident()
        {
            this.AccidentDocuments = new HashSet<AccidentDocument>();
            this.AccidentExpenses = new HashSet<AccidentExpense>();
        }
    
        public long PK_Accident { get; set; }
        public string DevelopersNote { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> FK_Vehicle { get; set; }
        public string TrackingID { get; set; }
        public string AccusedDriverStaffID { get; set; }
        public string AccusedDriverName { get; set; }
        public Nullable<System.DateTime> OccuranceDate { get; set; }
        public Nullable<long> FK_District { get; set; }
        public Nullable<long> FK_Upazila { get; set; }
        public string AccidentLocationDetail { get; set; }
        public string CurrentVehicleLocation { get; set; }
        public string DamageType { get; set; }
        public string DescriptionDuty { get; set; }
        public string DescriptionAccident { get; set; }
        public string PrimaryCause { get; set; }
        public Nullable<bool> IsManLoss { get; set; }
        public Nullable<int> ManLossCount { get; set; }
        public Nullable<bool> IsDamageProduct { get; set; }
        public Nullable<long> DamageProductCost { get; set; }
        public Nullable<bool> IsDamageVehicle { get; set; }
        public string DamageVehicleDetail { get; set; }
        public string OtherDamage { get; set; }
        public Nullable<long> RepairCost { get; set; }
        public Nullable<System.Guid> FK_DepoFollowUp { get; set; }
        public string ActionTakenStaffID { get; set; }
        public string ActionTakenStaffName { get; set; }
        public string Note { get; set; }
        public Nullable<byte> Status { get; set; }
        public string SettlementNote { get; set; }
        public Nullable<long> SettlementAmount { get; set; }
        public Nullable<System.Guid> FK_SettledByUser { get; set; }
        public Nullable<System.DateTime> SettledAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> FK_UpdatedByUser { get; set; }
        public Nullable<System.Guid> FK_DeletedByUser { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Depo Depo { get; set; }
        public virtual District District { get; set; }
        public virtual Upazila Upazila { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccidentDocument> AccidentDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccidentExpense> AccidentExpenses { get; set; }
    }
}
