//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppModule_AppAction
    {
        public long PK_AppModule_AppAction { get; set; }
        public long FK_AppModule { get; set; }
        public long FK_AppAction { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsAccessible { get; set; }
    
        public virtual AppAction AppAction { get; set; }
        public virtual AppModule AppModule { get; set; }
    }
}
