//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppModule()
        {
            this.AppModule_AppAction = new HashSet<AppModule_AppAction>();
            this.AppUser_AppModule = new HashSet<AppUser_AppModule>();
        }
    
        public long PK_AppModule { get; set; }
        public string Name { get; set; }
        public string VisibleName { get; set; }
        public string Link { get; set; }
        public Nullable<int> Serial { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppModule_AppAction> AppModule_AppAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUser_AppModule> AppUser_AppModule { get; set; }
    }
}
