//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserSurpervisedContructualCompany
    {
        public long PK_AppUserSurpervisedContructualCompany { get; set; }
        public System.Guid FK_AppUser { get; set; }
        public System.Guid FK_ContructualRequisitionCompany { get; set; }
        public bool WillSupervise { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual ContructualRequisitionCompany ContructualRequisitionCompany { get; set; }
    }
}
