//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserLoginHistory
    {
        public long PK_AppUserLoginHistory { get; set; }
        public System.Guid FK_AppUser { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime ExpirationTime { get; set; }
        public string Reason { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
