//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser_AppModule
    {
        public long PK_AppUser_AppModule { get; set; }
        public System.Guid FK_AppUser { get; set; }
        public long FK_AppModule { get; set; }
        public bool IsAccessible { get; set; }
    
        public virtual AppModule AppModule { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
