//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Vehicles = new HashSet<Vehicle>();
            this.Vehicles1 = new HashSet<Vehicle>();
        }
    
        public long RowSerial { get; set; }
        public System.Guid PK_Company { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid FK_GroupOfCompany { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsPruchaseCompany { get; set; }
        public Nullable<bool> IsUserCompany { get; set; }
        public string CompanyRegistrationNumber { get; set; }
        public string CompnayAddress { get; set; }
        public string ExternalOwnersFullName { get; set; }
        public string ExternalOwnersNID { get; set; }
        public string ExternalOwnersFathersName { get; set; }
        public string ExternalOwnersContactNumber { get; set; }
        public string ExternalOwnersAddress { get; set; }
    
        public virtual GroupOfCompany GroupOfCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles1 { get; set; }
    }
}
