//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Helper
    {
        public long RowSerial { get; set; }
        public System.Guid PK_Helper { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> FK_Depo { get; set; }
        public string UniqueIDNumber { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string NID { get; set; }
    
        public virtual Depo Depo { get; set; }
    }
}
