//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiredVehicleDriver
    {
        public long RowSerial { get; set; }
        public string DevelopersNote { get; set; }
        public System.Guid PK_HiredVehicleDriver { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid FK_Vehicle { get; set; }
        public string DriverName { get; set; }
        public string DriverLiceneseNumber { get; set; }
        public string DriverLicenseType { get; set; }
        public string DriverContactNumber { get; set; }
        public string DriverFatherName { get; set; }
        public string DriverAddressVillage { get; set; }
        public string DriverAddressPostOfiice { get; set; }
        public string DriverAddressThana { get; set; }
        public string DriverAddressDistrict { get; set; }
        public string DriverNID { get; set; }
        public string DriverImageLocation { get; set; }
        public string DriverLicenseImageLocation { get; set; }
        public Nullable<long> DriverSalary { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> FK_UpdatedByUser { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
