//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstantRequisition
    {
        public long PK_InstantRequisition { get; set; }
        public bool IsDeleted { get; set; }
        public int Status { get; set; }
        public System.Guid FK_RequisitionAgent { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.Guid> REF_FK_Depo { get; set; }
        public System.Guid FK_Vehicle { get; set; }
        public string DriverStaffID { get; set; }
        public string DriverName { get; set; }
        public string HelperInfo { get; set; }
        public Nullable<System.Guid> FK_Depo_Booking { get; set; }
        public Nullable<System.Guid> FK_Depo_Destination { get; set; }
        public string StartingLocation { get; set; }
        public Nullable<double> StartingLatitude { get; set; }
        public Nullable<double> StartingLongitude { get; set; }
        public string FinishingLocation { get; set; }
        public Nullable<double> FinishingLatitude { get; set; }
        public Nullable<double> FinishingLongitude { get; set; }
        public long TripFare1 { get; set; }
        public Nullable<long> AdvancedToDriver1 { get; set; }
        public Nullable<double> Distance_Empty1 { get; set; }
        public Nullable<double> KPL_Empty1 { get; set; }
        public Nullable<double> Distance_Loaded1 { get; set; }
        public Nullable<double> KPL_Loaded1 { get; set; }
        public Nullable<double> Distance_Loaded_8_To_12_Tons_Out1 { get; set; }
        public Nullable<double> KPL_Loaded_8_To_12_Tons_Out1 { get; set; }
        public Nullable<double> Distance_Loaded_12_To_25_Tons_Out1 { get; set; }
        public Nullable<double> KPL_Loaded_12_To_25_Tons_Out1 { get; set; }
        public Nullable<double> FuelConsumedLitre1 { get; set; }
        public Nullable<double> FuelPricePerLitre1 { get; set; }
        public Nullable<decimal> FuelExpence1 { get; set; }
        public Nullable<bool> FuelExpenceGivenCashOrOil { get; set; }
        public Nullable<decimal> StayCharge1 { get; set; }
        public Nullable<decimal> TripBillDriver1 { get; set; }
        public Nullable<decimal> TripBillHelper1 { get; set; }
        public Nullable<decimal> EntertainmentACharge1 { get; set; }
        public Nullable<decimal> RepairCharge1 { get; set; }
        public Nullable<decimal> BridgeTollFerryCharge1 { get; set; }
        public Nullable<decimal> OpenBodyCharge1 { get; set; }
        public string TransportAgencyName { get; set; }
        public string TransportAgencyContactNumber { get; set; }
        public string ResponsibleParsonName { get; set; }
        public string ResponsibleParsonContactNumber { get; set; }
        public string Note1 { get; set; }
        public Nullable<decimal> TotalParent1 { get; set; }
        public string PolicyKey { get; set; }
        public string PolicyDetail { get; set; }
        public Nullable<System.DateTime> BillPaidAt { get; set; }
        public Nullable<System.Guid> FK_AppUser_BillPaidBy { get; set; }
        public Nullable<decimal> DriversMoney2 { get; set; }
        public Nullable<decimal> HelpersMoney2 { get; set; }
        public Nullable<decimal> TPTsMoney2 { get; set; }
        public Nullable<decimal> ScaleCharge2 { get; set; }
        public Nullable<decimal> NightStayCharge2 { get; set; }
        public Nullable<decimal> StayCharge2 { get; set; }
        public Nullable<double> Distance_Empty2 { get; set; }
        public Nullable<double> KPL_Empty2 { get; set; }
        public Nullable<double> Distance_Loaded2 { get; set; }
        public Nullable<double> KPL_Loaded2 { get; set; }
        public Nullable<double> Distance_Loaded_8_To_12_Tons_Out2 { get; set; }
        public Nullable<double> KPL_Loaded_8_To_12_Tons_Out2 { get; set; }
        public Nullable<double> Distance_Loaded_12_To_25_Tons_Out2 { get; set; }
        public Nullable<double> KPL_Loaded_12_To_25_Tons_Out2 { get; set; }
        public Nullable<double> FuelConsumedLitre2 { get; set; }
        public Nullable<double> FuelPricePerLitre2 { get; set; }
        public Nullable<decimal> FuelExpence2 { get; set; }
        public Nullable<decimal> LaborCharge2 { get; set; }
        public Nullable<decimal> RepairCharge2 { get; set; }
        public Nullable<decimal> BridgeTollFerryCharge2 { get; set; }
        public Nullable<decimal> EntertainmentCCharge2 { get; set; }
        public Nullable<decimal> ParkingCharge2 { get; set; }
        public Nullable<decimal> TransportCommissionCharge2 { get; set; }
        public Nullable<decimal> EntertainmentACharge2 { get; set; }
        public Nullable<decimal> GiveDemerageCharge2 { get; set; }
        public Nullable<decimal> TotalGiven2 { get; set; }
        public string Note2 { get; set; }
        public Nullable<double> Distance_Empty3 { get; set; }
        public Nullable<double> KPL_Empty3 { get; set; }
        public Nullable<double> Distance_Loaded3 { get; set; }
        public Nullable<double> KPL_Loaded3 { get; set; }
        public Nullable<double> Distance_Loaded_8_To_12_Tons_Out3 { get; set; }
        public Nullable<double> KPL_Loaded_8_To_12_Tons_Out3 { get; set; }
        public Nullable<double> Distance_Loaded_12_To_25_Tons_Out3 { get; set; }
        public Nullable<double> KPL_Loaded_12_To_25_Tons_Out3 { get; set; }
        public Nullable<double> FuelConsumedLitre3 { get; set; }
        public Nullable<double> FuelPricePerLitre3 { get; set; }
        public Nullable<decimal> FuelExpence3 { get; set; }
        public Nullable<decimal> BridgeTollFerryCharge3 { get; set; }
        public Nullable<decimal> TakeDemerageCharge3 { get; set; }
        public Nullable<decimal> TPTsMoney3 { get; set; }
        public Nullable<decimal> OthersCharge3 { get; set; }
        public Nullable<decimal> TotalTaken3 { get; set; }
        public Nullable<decimal> NetProfit3 { get; set; }
        public Nullable<decimal> GrossTaken3 { get; set; }
        public string DepositToAccountLocation { get; set; }
        public string Note3 { get; set; }
        public Nullable<System.DateTime> AdjustedAt { get; set; }
        public Nullable<System.Guid> FK_AppUser_AdjustedBy { get; set; }
        public Nullable<decimal> NetProfit4 { get; set; }
        public Nullable<decimal> GrossProfit4 { get; set; }
        public string DepositeToAcccountLocation { get; set; }
        public string MRR { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Depo Depo { get; set; }
        public virtual Depo Depo1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
