//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterCompanyRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InterCompanyRequisition()
        {
            this.InterCompanyRequisition_ExternalTroller = new HashSet<InterCompanyRequisition_ExternalTroller>();
            this.InterCompanyRequisition_ExternalVehicle = new HashSet<InterCompanyRequisition_ExternalVehicle>();
            this.InterCompanyRequisition_InternalVehicle = new HashSet<InterCompanyRequisition_InternalVehicle>();
            this.InterCompanyRequisitionBiddings = new HashSet<InterCompanyRequisitionBidding>();
        }
    
        public long RowSerial { get; set; }
        public System.Guid PK_InterCompanyRequisition { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsTest { get; set; }
        public Nullable<int> WantedCount { get; set; }
        public Nullable<int> AcceptedCount { get; set; }
        public System.DateTime PossibleJourneyStartDateTime { get; set; }
        public System.Guid FK_AppUser_Client { get; set; }
        public Nullable<System.Guid> FK_ReferenceDepo { get; set; }
        public Nullable<System.Guid> FK_AppUser_Approver { get; set; }
        public Nullable<System.Guid> FK_InterCompanyRequisitionLocation_From { get; set; }
        public string StartingLocation { get; set; }
        public Nullable<double> StartingLatitude { get; set; }
        public Nullable<double> StartingLongitude { get; set; }
        public Nullable<System.Guid> FK_InterCompanyRequisitionLocation_To { get; set; }
        public string FinishingLocation { get; set; }
        public Nullable<double> FinishingLatitude { get; set; }
        public Nullable<double> FinishingLongitude { get; set; }
        public Nullable<int> FK_RequisitionVehicleType { get; set; }
        public string VehicleType { get; set; }
        public string VehicleTypeLayer1 { get; set; }
        public string VehicleTypeLayer1_english { get; set; }
        public string VehicleTypeLayer1_bangla { get; set; }
        public string VehicleTypeLayer2 { get; set; }
        public string VehicleTypeLayer2_english { get; set; }
        public string VehicleTypeLayer2_bangla { get; set; }
        public string VehicleTypeLayer3 { get; set; }
        public string VehicleTypeLayer3_english { get; set; }
        public string VehicleTypeLayer3_bangla { get; set; }
        public string VehicleCapacity { get; set; }
        public string ClientNote { get; set; }
        public string ApproverNote { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> IsEndLevelRequisition { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> VerifiedAt { get; set; }
        public Nullable<int> HiredVehicleCount_Internal { get; set; }
        public Nullable<int> HiredVehicleCount_External { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Depo Depo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisition_ExternalTroller> InterCompanyRequisition_ExternalTroller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisition_ExternalVehicle> InterCompanyRequisition_ExternalVehicle { get; set; }
        public virtual InterCompanyRequisitionLocation InterCompanyRequisitionLocation { get; set; }
        public virtual InterCompanyRequisitionLocation InterCompanyRequisitionLocation1 { get; set; }
        public virtual RequisitionVehicleType RequisitionVehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisition_InternalVehicle> InterCompanyRequisition_InternalVehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisitionBidding> InterCompanyRequisitionBiddings { get; set; }
    }
}
