//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterCompanyRequisition_InternalVehicle
    {
        public long RowSerial { get; set; }
        public System.Guid PK_InterCompanyRequisition_InternalVehicle { get; set; }
        public System.Guid FK_InterCompanyRequisition { get; set; }
        public System.Guid FK_Vehicle { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Note { get; set; }
    
        public virtual InterCompanyRequisition InterCompanyRequisition { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
