//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterCompanyRequisitionLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InterCompanyRequisitionLocation()
        {
            this.InterCompanyRequisitions = new HashSet<InterCompanyRequisition>();
            this.InterCompanyRequisitions1 = new HashSet<InterCompanyRequisition>();
        }
    
        public long RowSerial { get; set; }
        public System.Guid PK_InterCompanyRequisitionLocation { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public string Cetegory { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.Guid> FK_UpdatedByUser { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> FK_DeletedByUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisition> InterCompanyRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisition> InterCompanyRequisitions1 { get; set; }
    }
}
