//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPLChangeLog
    {
        public long PK_KPLChangeLog { get; set; }
        public System.Guid FK_Vehicle { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<double> KPL_Loaded { get; set; }
        public Nullable<double> KPL_Loaded_Plastic { get; set; }
        public Nullable<double> KPL_Empty { get; set; }
        public Nullable<double> KPL_InterCity { get; set; }
        public Nullable<double> KPL_InterCHT { get; set; }
        public Nullable<double> KPL_Hill { get; set; }
        public Nullable<double> KPL_OnlyMover { get; set; }
        public Nullable<double> KPL_Loaded_8_To_12_Tons { get; set; }
        public Nullable<double> KPL_Loaded_12_To_25_Tons { get; set; }
        public Nullable<double> KPL_Loaded_8_To_12_Tons_Out { get; set; }
        public Nullable<double> KPL_Loaded_12_To_25_Tons_Out { get; set; }
    }
}
