//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationToLocationMapping
    {
        public long PK_LocationToLocationMapping { get; set; }
        public System.Guid FK_Location_1 { get; set; }
        public System.Guid FK_Location_2 { get; set; }
        public Nullable<int> StandardTravelTimeMinute { get; set; }
        public Nullable<int> StandardDistanceKM { get; set; }
    }
}
