//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceCase_PoliceCaseLaw
    {
        public long PK_PoliceCase_PoliceCaseLaw { get; set; }
        public System.Guid FK_PoliceCase { get; set; }
        public string FK_PoliceCaseLaw { get; set; }
    
        public virtual PoliceCase PoliceCase { get; set; }
        public virtual PoliceCaseLaw PoliceCaseLaw { get; set; }
    }
}
