//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_VehicleInOutHistoryDetail
    {
        public long PK { get; set; }
        public Nullable<System.Guid> USER_KEY { get; set; }
        public Nullable<System.Guid> FK_Vehicle { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public Nullable<System.Guid> FK_Depo { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}
