//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_TemperatureReport
    {
        public long PK_Report_TemperatureReport { get; set; }
        public Nullable<System.Guid> USER_KEY { get; set; }
        public Nullable<System.Guid> FK_Vehicle { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<double> Temperature { get; set; }
    }
}
