//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_VehicleConsolidatedReport
    {
        public long PK { get; set; }
        public string USER_KEY { get; set; }
        public string C_rowType { get; set; }
        public string ThisDate { get; set; }
        public string RegistrationNumber { get; set; }
        public string MobileNumber { get; set; }
        public string LastUpdate { get; set; }
        public string LastLocaitonNearName { get; set; }
        public string LastLocaitonNearDistance { get; set; }
        public string TotalHaltTime { get; set; }
        public string HaltCount { get; set; }
        public string AverageHaltTime { get; set; }
        public string MaximumHaltTime { get; set; }
        public string TotalRunTime { get; set; }
        public string TotalDistance { get; set; }
        public string MaximumSpeed { get; set; }
    }
}
