//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionAgentProposedDepo
    {
        public long PK_RequisitionAgentProposedDepo { get; set; }
        public System.Guid FK_RequisitionAgent { get; set; }
        public System.Guid FK_Depo { get; set; }
        public bool WillPropose { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Depo Depo { get; set; }
    }
}
