//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFID_EntryLog
    {
        public long ID { get; set; }
        public string TotalText_Raw { get; set; }
        public Nullable<long> FK_RFID_Entry { get; set; }
        public string GateID { get; set; }
        public Nullable<System.DateTime> EntryLogedAt { get; set; }
    }
}
