//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCall
    {
        public long RowSerial { get; set; }
        public string CallingMessage { get; set; }
        public string UserDefinedMessage { get; set; }
        public Nullable<System.DateTime> CallingTime { get; set; }
    }
}
