//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThirdEyeDBEntities : DbContext
    {
        public ThirdEyeDBEntities()
            : base("name=ThirdEyeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accident> Accidents { get; set; }
        public virtual DbSet<AccidentDocument> AccidentDocuments { get; set; }
        public virtual DbSet<AccidentExpense> AccidentExpenses { get; set; }
        public virtual DbSet<AlertEmail> AlertEmails { get; set; }
        public virtual DbSet<AlertEmailAttachedDepo> AlertEmailAttachedDepoes { get; set; }
        public virtual DbSet<AlertEmailLog> AlertEmailLogs { get; set; }
        public virtual DbSet<AppAction> AppActions { get; set; }
        public virtual DbSet<AppErrorLog> AppErrorLogs { get; set; }
        public virtual DbSet<AppMenu> AppMenus { get; set; }
        public virtual DbSet<AppModule> AppModules { get; set; }
        public virtual DbSet<AppModule_AppAction> AppModule_AppAction { get; set; }
        public virtual DbSet<AppPermission> AppPermissions { get; set; }
        public virtual DbSet<AppRole> AppRoles { get; set; }
        public virtual DbSet<AppRole_AppMenu> AppRole_AppMenu { get; set; }
        public virtual DbSet<AppRole_AppPermission> AppRole_AppPermission { get; set; }
        public virtual DbSet<AppRole_AppSubMenu> AppRole_AppSubMenu { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<AppSubMenu> AppSubMenus { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<AppUser_AppModule> AppUser_AppModule { get; set; }
        public virtual DbSet<AppUserAccessibleDepo> AppUserAccessibleDepoes { get; set; }
        public virtual DbSet<AppUserLoginHistory> AppUserLoginHistories { get; set; }
        public virtual DbSet<AppUserSurpervisedContructualCompany> AppUserSurpervisedContructualCompanies { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ContructualRequisition> ContructualRequisitions { get; set; }
        public virtual DbSet<ContructualRequisitionCompany> ContructualRequisitionCompanies { get; set; }
        public virtual DbSet<ContructualRequisitionDetail> ContructualRequisitionDetails { get; set; }
        public virtual DbSet<ContructualRequisitionDetailEntry> ContructualRequisitionDetailEntries { get; set; }
        public virtual DbSet<DairyVehicle> DairyVehicles { get; set; }
        public virtual DbSet<Dealer> Dealers { get; set; }
        public virtual DbSet<Depo> Depoes { get; set; }
        public virtual DbSet<DepoBorder> DepoBorders { get; set; }
        public virtual DbSet<DepoGroup> DepoGroups { get; set; }
        public virtual DbSet<DeviceData> DeviceDatas { get; set; }
        public virtual DbSet<DisplayMessage> DisplayMessages { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventDocument> EventDocuments { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<FinancingCompany> FinancingCompanies { get; set; }
        public virtual DbSet<GPS_DeviceChangeLog> GPS_DeviceChangeLog { get; set; }
        public virtual DbSet<GPS_DeviceExisting> GPS_DeviceExisting { get; set; }
        public virtual DbSet<GroupOfCompany> GroupOfCompanies { get; set; }
        public virtual DbSet<Helper> Helpers { get; set; }
        public virtual DbSet<HiredVehicleDriver> HiredVehicleDrivers { get; set; }
        public virtual DbSet<IndividualRequisition> IndividualRequisitions { get; set; }
        public virtual DbSet<IndividualRequisitionBidding> IndividualRequisitionBiddings { get; set; }
        public virtual DbSet<InstantRequisition> InstantRequisitions { get; set; }
        public virtual DbSet<InterCompanyRequisition> InterCompanyRequisitions { get; set; }
        public virtual DbSet<InterCompanyRequisition_ExternalTroller> InterCompanyRequisition_ExternalTroller { get; set; }
        public virtual DbSet<InterCompanyRequisition_ExternalVehicle> InterCompanyRequisition_ExternalVehicle { get; set; }
        public virtual DbSet<InterCompanyRequisition_InternalVehicle> InterCompanyRequisition_InternalVehicle { get; set; }
        public virtual DbSet<InterCompanyRequisitionBidding> InterCompanyRequisitionBiddings { get; set; }
        public virtual DbSet<InterCompanyRequisitionLocation> InterCompanyRequisitionLocations { get; set; }
        public virtual DbSet<KPLChangeLog> KPLChangeLogs { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationToLocationMapping> LocationToLocationMappings { get; set; }
        public virtual DbSet<LocationWiseGP> LocationWiseGPs { get; set; }
        public virtual DbSet<MapLocation> MapLocations { get; set; }
        public virtual DbSet<MobileMenu> MobileMenus { get; set; }
        public virtual DbSet<MobileRole> MobileRoles { get; set; }
        public virtual DbSet<MobileRole_MobileMenu> MobileRole_MobileMenu { get; set; }
        public virtual DbSet<MonthlyBillEntry> MonthlyBillEntries { get; set; }
        public virtual DbSet<PoliceCase> PoliceCases { get; set; }
        public virtual DbSet<PoliceCase_PoliceCaseLaw> PoliceCase_PoliceCaseLaw { get; set; }
        public virtual DbSet<PoliceCaseDocument> PoliceCaseDocuments { get; set; }
        public virtual DbSet<PoliceCaseLaw> PoliceCaseLaws { get; set; }
        public virtual DbSet<PRG_Type> PRG_Type { get; set; }
        public virtual DbSet<ReadyReport> ReadyReports { get; set; }
        public virtual DbSet<Report_ConsolidatedRport> Report_ConsolidatedRport { get; set; }
        public virtual DbSet<Report_TemperatureReport> Report_TemperatureReport { get; set; }
        public virtual DbSet<Report_TemperatureReport_Helper> Report_TemperatureReport_Helper { get; set; }
        public virtual DbSet<Report_VehicleConsolidatedReport> Report_VehicleConsolidatedReport { get; set; }
        public virtual DbSet<Report_VehicleHaltReadyReport_Helper> Report_VehicleHaltReadyReport_Helper { get; set; }
        public virtual DbSet<Report_VehicleHaltReadyReport_Helper_Helper> Report_VehicleHaltReadyReport_Helper_Helper { get; set; }
        public virtual DbSet<Report_VehicleHaltReport> Report_VehicleHaltReport { get; set; }
        public virtual DbSet<Report_VehicleHaltReport_Helper> Report_VehicleHaltReport_Helper { get; set; }
        public virtual DbSet<Report_VehicleHistory> Report_VehicleHistory { get; set; }
        public virtual DbSet<Report_VehicleHistoryDetail> Report_VehicleHistoryDetail { get; set; }
        public virtual DbSet<Report_VehicleInOutHistoryDetail> Report_VehicleInOutHistoryDetail { get; set; }
        public virtual DbSet<Requisition> Requisitions { get; set; }
        public virtual DbSet<RequisitionAgentNotification> RequisitionAgentNotifications { get; set; }
        public virtual DbSet<RequisitionAgentProposedDepo> RequisitionAgentProposedDepoes { get; set; }
        public virtual DbSet<RequisitionBusinessUnit> RequisitionBusinessUnits { get; set; }
        public virtual DbSet<RequisitionProductType> RequisitionProductTypes { get; set; }
        public virtual DbSet<RequisitionTrip> RequisitionTrips { get; set; }
        public virtual DbSet<RequisitionTrip_Finished> RequisitionTrip_Finished { get; set; }
        public virtual DbSet<RequisitionVehicleType> RequisitionVehicleTypes { get; set; }
        public virtual DbSet<RFID_AutoDistSuggession> RFID_AutoDistSuggession { get; set; }
        public virtual DbSet<RFID_AutoLetterSuggession> RFID_AutoLetterSuggession { get; set; }
        public virtual DbSet<RFID_Entry> RFID_Entry { get; set; }
        public virtual DbSet<RFID_EntryLog> RFID_EntryLog { get; set; }
        public virtual DbSet<RouteChart> RouteCharts { get; set; }
        public virtual DbSet<ServiceCall> ServiceCalls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TempMail> TempMails { get; set; }
        public virtual DbSet<TemporaryVehicle> TemporaryVehicles { get; set; }
        public virtual DbSet<TransportCompany> TransportCompanies { get; set; }
        public virtual DbSet<TripExpense> TripExpenses { get; set; }
        public virtual DbSet<Upazila> Upazilas { get; set; }
        public virtual DbSet<UserDesignation> UserDesignations { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleBrand> VehicleBrands { get; set; }
        public virtual DbSet<VehicleInOutManual> VehicleInOutManuals { get; set; }
        public virtual DbSet<VehicleInOutManualReason> VehicleInOutManualReasons { get; set; }
        public virtual DbSet<VehicleInOutManualTypesOfProduct> VehicleInOutManualTypesOfProducts { get; set; }
        public virtual DbSet<VehicleModel> VehicleModels { get; set; }
        public virtual DbSet<VehicleSharing> VehicleSharings { get; set; }
        public virtual DbSet<VehicleSharingBidding> VehicleSharingBiddings { get; set; }
        public virtual DbSet<VehicleSharingDemand> VehicleSharingDemands { get; set; }
        public virtual DbSet<VehicleSharingExternalTrip> VehicleSharingExternalTrips { get; set; }
        public virtual DbSet<VehicleSharingInternalTrip> VehicleSharingInternalTrips { get; set; }
        public virtual DbSet<VehicleSharingInternalTripAdjustment> VehicleSharingInternalTripAdjustments { get; set; }
        public virtual DbSet<VehicleTracking> VehicleTrackings { get; set; }
        public virtual DbSet<VehicleTrackingInformation> VehicleTrackingInformations { get; set; }
        public virtual DbSet<VehicleTrip> VehicleTrips { get; set; }
        public virtual DbSet<VehicleSharingAgentMapping> VehicleSharingAgentMappings { get; set; }
    }
}
