//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInOutManual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleInOutManual()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public long PK_VehicleInOutManual { get; set; }
        public string DevelopersNote { get; set; }
        public System.Guid FK_Vehicle { get; set; }
        public System.Guid FK_Depo { get; set; }
        public System.Guid FK_Location { get; set; }
        public Nullable<long> FK_PRG_Type { get; set; }
        public Nullable<bool> InOrOut { get; set; }
        public Nullable<System.Guid> FK_Depo_FromTo { get; set; }
        public System.Guid In_FK_CreatedByUser { get; set; }
        public string In_LoadOrEmpty { get; set; }
        public Nullable<long> In_FK_VehicleInOutManualTypesOfProduct { get; set; }
        public Nullable<long> In_FK_VehicleInOutManualReason { get; set; }
        public System.DateTime In_IssueDateTime { get; set; }
        public string In_IssuedDateTimeAutoOrManual { get; set; }
        public Nullable<bool> In_IsScannedEntry { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> Out_FK_CreatedByUser { get; set; }
        public string Out_LoadOrEmpty { get; set; }
        public Nullable<long> Out_FK_VehicleInOutManualTypesOfProduct { get; set; }
        public Nullable<long> Out_FK_VehicleInOutManualReason { get; set; }
        public Nullable<System.DateTime> Out_IssueDateTime { get; set; }
        public string Out_IssuedDateTimeAutoOrManual { get; set; }
        public Nullable<bool> Out_IsScannedEntry { get; set; }
        public string GPNumber { get; set; }
        public Nullable<long> StayTimeMinute { get; set; }
        public Nullable<long> OverStayTimeMinute { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Depo Depo { get; set; }
        public virtual Depo Depo1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual PRG_Type PRG_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual VehicleInOutManualReason VehicleInOutManualReason { get; set; }
        public virtual VehicleInOutManualReason VehicleInOutManualReason1 { get; set; }
        public virtual VehicleInOutManualTypesOfProduct VehicleInOutManualTypesOfProduct { get; set; }
        public virtual VehicleInOutManualTypesOfProduct VehicleInOutManualTypesOfProduct1 { get; set; }
    }
}
