//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Accidents = new HashSet<Accident>();
            this.Events = new HashSet<Event>();
            this.HiredVehicleDrivers = new HashSet<HiredVehicleDriver>();
            this.InstantRequisitions = new HashSet<InstantRequisition>();
            this.InterCompanyRequisition_ExternalVehicle = new HashSet<InterCompanyRequisition_ExternalVehicle>();
            this.InterCompanyRequisition_InternalVehicle = new HashSet<InterCompanyRequisition_InternalVehicle>();
            this.PoliceCases = new HashSet<PoliceCase>();
            this.RequisitionTrips = new HashSet<RequisitionTrip>();
            this.RequisitionTrip_Finished = new HashSet<RequisitionTrip_Finished>();
            this.VehicleInOutManuals = new HashSet<VehicleInOutManual>();
            this.VehicleSharingExternalTrips = new HashSet<VehicleSharingExternalTrip>();
            this.VehicleSharingInternalTrips = new HashSet<VehicleSharingInternalTrip>();
            this.VehicleTrips = new HashSet<VehicleTrip>();
        }
    
        public long RowSerial { get; set; }
        public string DevelopersNote { get; set; }
        public System.Guid PK_Vehicle { get; set; }
        public string RegistrationNumber { get; set; }
        public string FID { get; set; }
        public string PhysicalDocumnetLocation { get; set; }
        public string OWN_MHT_DHT { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> FK_Company { get; set; }
        public System.Guid FK_Depo { get; set; }
        public Nullable<System.Guid> FK_DepoGroup { get; set; }
        public Nullable<System.Guid> FK_VehicleModel { get; set; }
        public Nullable<System.DateTime> RegisrationDate { get; set; }
        public string ChassisNumber { get; set; }
        public string EngineNumber { get; set; }
        public Nullable<long> EngineCC { get; set; }
        public string VehicleType { get; set; }
        public string FuelType { get; set; }
        public string GpsDeviceModel { get; set; }
        public string GpsIMEINumber { get; set; }
        public string GpsMobileNumber { get; set; }
        public Nullable<double> CapacityTon { get; set; }
        public Nullable<int> CapacitySeat { get; set; }
        public Nullable<bool> NumberPlate_IsDigital { get; set; }
        public Nullable<bool> changeImage { get; set; }
        public string ImageLocation { get; set; }
        public Nullable<long> Internal_VehiclePrice { get; set; }
        public Nullable<System.DateTime> Internal_PurchaseDate { get; set; }
        public Nullable<System.Guid> Internal_FK_FinancingCompany { get; set; }
        public Nullable<System.Guid> Internal_FK_PurchasingCompany { get; set; }
        public Nullable<bool> Internal_ShowTemperature { get; set; }
        public string Internal_VehicleContactNumber { get; set; }
        public string Internal_FinancingAgrementNumber { get; set; }
        public Nullable<int> Internal_FinancingAgrementNumberOfVehicle { get; set; }
        public Nullable<System.DateTime> Internal_FinancingAgrementMaturityDate { get; set; }
        public string Internal_FinancingAgrementGRN_MRR { get; set; }
        public Nullable<System.DateTime> Internal_FinancingAgrementGRN_MRR_Date { get; set; }
        public Nullable<bool> Internal_FinancingAgrementIsMatured { get; set; }
        public Nullable<System.Guid> Internal_FinancingAgrementUpdatedBy { get; set; }
        public Nullable<System.Guid> Internal_FinancingAgrementMaturityUpdatedBy { get; set; }
        public Nullable<double> Internal_KPL_Empty { get; set; }
        public Nullable<double> Internal_KPL_Loaded { get; set; }
        public Nullable<double> Internal_KPL_Loaded_Plastic { get; set; }
        public Nullable<double> Internal_KPL_InterCity { get; set; }
        public Nullable<double> Internal_KPL_InterCHT { get; set; }
        public Nullable<double> Internal_KPL_Hill { get; set; }
        public Nullable<double> Internal_KPL_OnlyMover { get; set; }
        public Nullable<double> Internal_KPL_Loaded_8_To_12_Tons { get; set; }
        public Nullable<double> Internal_KPL_Loaded_12_To_25_Tons { get; set; }
        public Nullable<double> Internal_KPL_Loaded_8_To_12_Tons_Out { get; set; }
        public Nullable<double> Internal_KPL_Loaded_12_To_25_Tons_Out { get; set; }
        public Nullable<double> MHT_DHT_VehicleSize { get; set; }
        public Nullable<bool> MHT_DHT_IsNewDriver { get; set; }
        public string MHT_DHT_DriverName { get; set; }
        public string MHT_DHT_DriverLiceneseNumber { get; set; }
        public string MHT_DHT_DriverLicenseType { get; set; }
        public string MHT_DHT_DriverContactNumber { get; set; }
        public string MHT_DHT_DriverFatherName { get; set; }
        public string MHT_DHT_DriverAddressVillage { get; set; }
        public string MHT_DHT_DriverAddressPostOfiice { get; set; }
        public string MHT_DHT_DriverAddressThana { get; set; }
        public string MHT_DHT_DriverAddressDistrict { get; set; }
        public string MHT_DHT_DriverNID { get; set; }
        public string MHT_DHT_DriverImageLocation { get; set; }
        public Nullable<bool> MHT_DHT_DriverImage_changeImage { get; set; }
        public string MHT_DHT_DriverLicenseImageLocation { get; set; }
        public Nullable<bool> MHT_DHT_DriverLicenseImage_changeImage { get; set; }
        public Nullable<long> MHT_DHT_DriverSalary { get; set; }
        public string MHT_DHT_OwnerName { get; set; }
        public string MHT_DHT_OwnerFatherName { get; set; }
        public string MHT_DHT_OwnerAddressVillage { get; set; }
        public string MHT_DHT_OwnerAddressPostOffice { get; set; }
        public string MHT_DHT_OwnerAddressThana { get; set; }
        public string MHT_DHT_OwnerAddressDistrict { get; set; }
        public string MHT_DHT_OwnerContactNumber { get; set; }
        public string MHT_DHT_OwnerNID { get; set; }
        public Nullable<System.DateTime> MHT_AgreementFrom { get; set; }
        public Nullable<System.DateTime> MHT_AgreementTo { get; set; }
        public Nullable<long> MHT_MonthlyRentRate { get; set; }
        public Nullable<bool> MHT_changeDeedImage { get; set; }
        public string MHT_DeedImageLocation { get; set; }
        public Nullable<bool> DepoInOrOut { get; set; }
        public Nullable<System.Guid> FK_DepoInOut { get; set; }
        public Nullable<System.DateTime> DepoInOutTime { get; set; }
        public string DepoInOut_Load_Unload_Workshop { get; set; }
        public Nullable<bool> LocationInOrOut { get; set; }
        public Nullable<System.Guid> FK_LocationInOut { get; set; }
        public Nullable<System.DateTime> LocationInOutTime { get; set; }
        public string LocationInOut_Load_Unload_Workshop { get; set; }
        public Nullable<long> FK_VehicleInOutManual_Last { get; set; }
        public Nullable<long> FK_VehicleInOutManualWorkshop { get; set; }
        public Nullable<long> DepoStayMaximumTimeMinute { get; set; }
        public Nullable<long> FK_VehicleSharingInternalTrip_Pending { get; set; }
        public Nullable<long> FK_VehicleSharingInternalTrip_Current { get; set; }
        public Nullable<long> FK_VehicleSharingExternalTrip_Current { get; set; }
        public Nullable<long> FK_RequisitionTrip_Pending { get; set; }
        public Nullable<long> FK_RequisitionTrip_Current { get; set; }
        public Nullable<System.Guid> FK_RequisitionTrip_CurrentAssigner { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> FK_UpdatedByUser { get; set; }
        public Nullable<System.Guid> FK_DeletedByUser { get; set; }
        public Nullable<bool> IsAddedToSaleSoft { get; set; }
        public string SaleSoftRequestTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accident> Accidents { get; set; }
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        public virtual DairyVehicle DairyVehicle { get; set; }
        public virtual Depo Depo { get; set; }
        public virtual Depo Depo1 { get; set; }
        public virtual DepoGroup DepoGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual FinancingCompany FinancingCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HiredVehicleDriver> HiredVehicleDrivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantRequisition> InstantRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisition_ExternalVehicle> InterCompanyRequisition_ExternalVehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisition_InternalVehicle> InterCompanyRequisition_InternalVehicle { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoliceCase> PoliceCases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionTrip> RequisitionTrips { get; set; }
        public virtual RequisitionTrip RequisitionTrip { get; set; }
        public virtual RequisitionTrip RequisitionTrip1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionTrip_Finished> RequisitionTrip_Finished { get; set; }
        public virtual VehicleInOutManual VehicleInOutManual { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
        public virtual VehicleSharingInternalTrip VehicleSharingInternalTrip { get; set; }
        public virtual VehicleSharingInternalTrip VehicleSharingInternalTrip1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleInOutManual> VehicleInOutManuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingExternalTrip> VehicleSharingExternalTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingInternalTrip> VehicleSharingInternalTrips { get; set; }
        public virtual VehicleTrackingInformation VehicleTrackingInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleTrip> VehicleTrips { get; set; }
    }
}
