//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSharing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleSharing()
        {
            this.VehicleSharingBiddings = new HashSet<VehicleSharingBidding>();
            this.VehicleSharingDemands = new HashSet<VehicleSharingDemand>();
            this.VehicleSharingInternalTrips = new HashSet<VehicleSharingInternalTrip>();
        }
    
        public long PK_VehicleSharing { get; set; }
        public Nullable<bool> LoadedOrEmpty { get; set; }
        public Nullable<double> WantedCount { get; set; }
        public System.DateTime PossibleJourneyStartDateTime { get; set; }
        public Nullable<double> AcceptedCount { get; set; }
        public System.Guid FK_AppUser_Client { get; set; }
        public Nullable<System.Guid> FK_ReferenceDepo { get; set; }
        public Nullable<System.Guid> FK_AppUser_Approver { get; set; }
        public Nullable<System.Guid> FK_Depo_From { get; set; }
        public string StartingLocation { get; set; }
        public Nullable<System.Guid> FK_Depo_To { get; set; }
        public string FinishingLocation { get; set; }
        public Nullable<double> DistanceGoogle { get; set; }
        public int FK_RequisitionVehicleType { get; set; }
        public string VehicleType { get; set; }
        public string VehicleCapacity { get; set; }
        public string TrackingID { get; set; }
        public Nullable<System.Guid> FK_AppUser_Assigner { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsTest { get; set; }
        public string SharingNote { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> KeepBidOpenUntil { get; set; }
        public Nullable<bool> IsExternalAdvertised { get; set; }
        public Nullable<double> ExternalWantedCount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> LockedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual AppUser AppUser2 { get; set; }
        public virtual Depo Depo { get; set; }
        public virtual Depo Depo1 { get; set; }
        public virtual RequisitionVehicleType RequisitionVehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingBidding> VehicleSharingBiddings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingDemand> VehicleSharingDemands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingInternalTrip> VehicleSharingInternalTrips { get; set; }
    }
}
