//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSharingAgentMapping
    {
        public long PK_VehicleSharingAgentMapping { get; set; }
        public System.Guid FK_AppUser_InternalAgent { get; set; }
        public System.Guid FK_AppUser_ExternalAgent { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
    }
}
