//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequisitionSynchronizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTrip
    {
        public long RowSerial { get; set; }
        public System.Guid PK_VehicleTrip { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid FK_Vehicle { get; set; }
        public Nullable<System.Guid> FK_Depo_To { get; set; }
        public string OWN_MHT_DHT { get; set; }
        public string DHT_PartyPoint { get; set; }
        public System.Guid FK_Depo_From { get; set; }
        public string PartyPoint { get; set; }
        public Nullable<long> FreshChallan { get; set; }
        public Nullable<long> Toll { get; set; }
        public Nullable<long> Bridge { get; set; }
        public Nullable<long> Ferry { get; set; }
        public Nullable<long> CityCoorporation_LaborTrustChanda { get; set; }
        public Nullable<long> Eant_A { get; set; }
        public Nullable<long> OpenTruck { get; set; }
        public Nullable<long> Van_Rickshaw_Boat_TrollerRent { get; set; }
        public Nullable<long> AllowanceDriver { get; set; }
        public Nullable<long> AllowanceHelper { get; set; }
        public Nullable<long> MobileBill { get; set; }
        public Nullable<long> LandPort_Export_LCStation_AnotherPartyPoint_Workshop { get; set; }
        public Nullable<long> LoadUnloadPoint { get; set; }
        public Nullable<long> NightBill { get; set; }
        public Nullable<long> Conveyance { get; set; }
        public Nullable<long> CarriageOutword { get; set; }
        public Nullable<long> FactoryDiesel { get; set; }
        public Nullable<long> FactoryGas { get; set; }
        public Nullable<long> FactoryOcten { get; set; }
        public Nullable<long> FactoryMobil { get; set; }
        public Nullable<long> Others { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> FK_UpdatedByUser { get; set; }
        public Nullable<System.Guid> FK_DeletedByUser { get; set; }
    
        public virtual Depo Depo { get; set; }
        public virtual Depo Depo1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
