//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccidentExpense
    {
        public long PK_AccidentExpense { get; set; }
        public string DevelopersNote { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> FK_Accident { get; set; }
        public string TrackingID { get; set; }
        public Nullable<System.DateTime> OccuranceDate { get; set; }
        public Nullable<long> PaidAmount { get; set; }
        public string Purpose { get; set; }
        public Nullable<byte> Status { get; set; }
        public string InternalTakerStaffID { get; set; }
        public string InternalTakerStaffName { get; set; }
        public string ExternalTakerName { get; set; }
        public string ExternalTakerContactNumber { get; set; }
        public string ExternalTakerContactAddress { get; set; }
        public Nullable<System.Guid> FK_PaidByUser { get; set; }
        public Nullable<System.DateTime> PaidAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> FK_UpdatedByUser { get; set; }
        public Nullable<System.Guid> FK_DeletedByUser { get; set; }
    
        public virtual Accident Accident { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
