//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertEmailAttachedDepo
    {
        public long PK_AlertEmailAttachedDepo { get; set; }
        public System.Guid FK_AlertEmail { get; set; }
        public System.Guid FK_Depo { get; set; }
        public Nullable<bool> IsAttachable { get; set; }
    
        public virtual AlertEmail AlertEmail { get; set; }
        public virtual Depo Depo { get; set; }
    }
}
