//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertEmail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlertEmail()
        {
            this.AlertEmailAttachedDepoes = new HashSet<AlertEmailAttachedDepo>();
        }
    
        public System.Guid PK_AlertEmail { get; set; }
        public string MailAddress { get; set; }
        public Nullable<int> MailLevel { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> EventAlert_1 { get; set; }
        public Nullable<bool> EventAlert_2 { get; set; }
        public Nullable<bool> EventAlert_3 { get; set; }
        public Nullable<bool> PoliceCaseAlert_1 { get; set; }
        public Nullable<bool> PoliceCaseAlert_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertEmailAttachedDepo> AlertEmailAttachedDepoes { get; set; }
    }
}
