//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppUser()
        {
            this.Accidents = new HashSet<Accident>();
            this.Accidents1 = new HashSet<Accident>();
            this.AccidentExpenses = new HashSet<AccidentExpense>();
            this.AppUser_AppMenu = new HashSet<AppUser_AppMenu>();
            this.AppUser_AppPermission = new HashSet<AppUser_AppPermission>();
            this.AppUser_AppSubMenu = new HashSet<AppUser_AppSubMenu>();
            this.AppUserAccessibleDepoes = new HashSet<AppUserAccessibleDepo>();
            this.AppUserLoginHistories = new HashSet<AppUserLoginHistory>();
            this.AppUserSurpervisedContructualCompanies = new HashSet<AppUserSurpervisedContructualCompany>();
            this.ContructualRequisitions = new HashSet<ContructualRequisition>();
            this.ContructualRequisitionDetailEntries = new HashSet<ContructualRequisitionDetailEntry>();
            this.ContructualRequisitionDetailEntries1 = new HashSet<ContructualRequisitionDetailEntry>();
            this.IndividualRequisitions = new HashSet<IndividualRequisition>();
            this.IndividualRequisitionBiddings = new HashSet<IndividualRequisitionBidding>();
            this.InstantRequisitions = new HashSet<InstantRequisition>();
            this.InterCompanyRequisitions = new HashSet<InterCompanyRequisition>();
            this.InterCompanyRequisitions1 = new HashSet<InterCompanyRequisition>();
            this.InterCompanyRequisitionBiddings = new HashSet<InterCompanyRequisitionBidding>();
            this.LoadingBayUtilizations = new HashSet<LoadingBayUtilization>();
            this.LoadingBayUtilizations1 = new HashSet<LoadingBayUtilization>();
            this.Mappings = new HashSet<Mapping>();
            this.Mappings1 = new HashSet<Mapping>();
            this.ParkingInOuts = new HashSet<ParkingInOut>();
            this.ReceivingRequests = new HashSet<ReceivingRequest>();
            this.ReceivingRequests1 = new HashSet<ReceivingRequest>();
            this.ReceivingRequests2 = new HashSet<ReceivingRequest>();
            this.Requisitions = new HashSet<Requisition>();
            this.Requisitions1 = new HashSet<Requisition>();
            this.RequisitionAgentNotifications = new HashSet<RequisitionAgentNotification>();
            this.RequisitionAgentProposedDepoes = new HashSet<RequisitionAgentProposedDepo>();
            this.RequisitionTrips = new HashSet<RequisitionTrip>();
            this.RequisitionTrip_Finished = new HashSet<RequisitionTrip_Finished>();
            this.TemporaryVehicles = new HashSet<TemporaryVehicle>();
            this.VehicleInOutManuals = new HashSet<VehicleInOutManual>();
            this.VehicleInOutManuals1 = new HashSet<VehicleInOutManual>();
            this.VehicleSharings = new HashSet<VehicleSharing>();
            this.VehicleSharings1 = new HashSet<VehicleSharing>();
            this.VehicleSharings2 = new HashSet<VehicleSharing>();
            this.VehicleSharingAgentMappings = new HashSet<VehicleSharingAgentMapping>();
            this.VehicleSharingAgentMappings1 = new HashSet<VehicleSharingAgentMapping>();
            this.VehicleSharingBiddings = new HashSet<VehicleSharingBidding>();
            this.VehicleSharingDemands = new HashSet<VehicleSharingDemand>();
            this.VehicleSharingExternalTrips = new HashSet<VehicleSharingExternalTrip>();
            this.VehicleSharingExternalTrips1 = new HashSet<VehicleSharingExternalTrip>();
            this.VehicleSharingExternalTrips2 = new HashSet<VehicleSharingExternalTrip>();
            this.VehicleSharingInternalTrips = new HashSet<VehicleSharingInternalTrip>();
            this.VehicleSharingInternalTrips1 = new HashSet<VehicleSharingInternalTrip>();
            this.VehicleSharingInternalTrips2 = new HashSet<VehicleSharingInternalTrip>();
            this.VehicleSharingInternalTrips3 = new HashSet<VehicleSharingInternalTrip>();
            this.VehicleSharingInternalTrips4 = new HashSet<VehicleSharingInternalTrip>();
            this.VehicleSharingInternalTripAdjustments = new HashSet<VehicleSharingInternalTripAdjustment>();
            this.VehicleSharingInternalTripAdjustments1 = new HashSet<VehicleSharingInternalTripAdjustment>();
        }
    
        public long RowSerial { get; set; }
        public System.Guid PK_User { get; set; }
        public string DevelopersNote { get; set; }
        public string FID { get; set; }
        public string IMEI { get; set; }
        public Nullable<bool> IsSingleDeviceAccess { get; set; }
        public string DeviceId { get; set; }
        public Nullable<bool> IsNotifiable { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsBanned { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AppVersionCode { get; set; }
        public string PRG_Type { get; set; }
        public string AppUserType { get; set; }
        public string AppUserSubType { get; set; }
        public Nullable<long> FK_AppRole { get; set; }
        public Nullable<long> FK_MobileRole { get; set; }
        public string UniqueIDNumber { get; set; }
        public string Password_Encrypted { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> FK_TransportCompany { get; set; }
        public Nullable<System.Guid> FK_ContructualRequisitionCompany { get; set; }
        public string FullName { get; set; }
        public string HGroupName { get; set; }
        public string HCompany { get; set; }
        public string HDepartment { get; set; }
        public string HLocationName { get; set; }
        public string HDesignation { get; set; }
        public string HSatus { get; set; }
        public string HGender { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string ContactAddress { get; set; }
        public System.Guid FK_Depo { get; set; }
        public Nullable<System.Guid> FK_Location { get; set; }
        public Nullable<System.DateTime> LoginTryDateTime { get; set; }
        public Nullable<bool> LoginTryStatus { get; set; }
        public Nullable<System.DateTime> LoginHRIS_Update { get; set; }
        public Nullable<bool> PermissionAdd { get; set; }
        public Nullable<bool> PermissionEdit { get; set; }
        public Nullable<bool> PermissionView { get; set; }
        public Nullable<bool> PermissionDelete { get; set; }
        public Nullable<bool> PermissionAdmin { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.Guid> FK_UpdatedByUser { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> FK_DeletedByUser { get; set; }
        public Nullable<bool> InActiveSessionCheck { get; set; }
        public Nullable<bool> IsRegistrationCompleted { get; set; }
        public Nullable<long> FK_VehicleSharingInternalTrip_Pending { get; set; }
        public Nullable<long> FK_VehicleSharingInternalTrip_Current { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accident> Accidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accident> Accidents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccidentExpense> AccidentExpenses { get; set; }
        public virtual AppRole AppRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUser_AppMenu> AppUser_AppMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUser_AppPermission> AppUser_AppPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUser_AppSubMenu> AppUser_AppSubMenu { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual AppUser AppUser2 { get; set; }
        public virtual AppUser AppUser11 { get; set; }
        public virtual AppUser AppUser3 { get; set; }
        public virtual ContructualRequisitionCompany ContructualRequisitionCompany { get; set; }
        public virtual Depo Depo { get; set; }
        public virtual Location Location { get; set; }
        public virtual MobileRole MobileRole { get; set; }
        public virtual TransportCompany TransportCompany { get; set; }
        public virtual VehicleSharingInternalTrip VehicleSharingInternalTrip { get; set; }
        public virtual VehicleSharingInternalTrip VehicleSharingInternalTrip1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserAccessibleDepo> AppUserAccessibleDepoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserLoginHistory> AppUserLoginHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserSurpervisedContructualCompany> AppUserSurpervisedContructualCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContructualRequisition> ContructualRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContructualRequisitionDetailEntry> ContructualRequisitionDetailEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContructualRequisitionDetailEntry> ContructualRequisitionDetailEntries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualRequisition> IndividualRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualRequisitionBidding> IndividualRequisitionBiddings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantRequisition> InstantRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisition> InterCompanyRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisition> InterCompanyRequisitions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterCompanyRequisitionBidding> InterCompanyRequisitionBiddings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadingBayUtilization> LoadingBayUtilizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadingBayUtilization> LoadingBayUtilizations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapping> Mappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mapping> Mappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingInOut> ParkingInOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivingRequest> ReceivingRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivingRequest> ReceivingRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivingRequest> ReceivingRequests2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisition> Requisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisition> Requisitions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionAgentNotification> RequisitionAgentNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionAgentProposedDepo> RequisitionAgentProposedDepoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionTrip> RequisitionTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionTrip_Finished> RequisitionTrip_Finished { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemporaryVehicle> TemporaryVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleInOutManual> VehicleInOutManuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleInOutManual> VehicleInOutManuals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharing> VehicleSharings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharing> VehicleSharings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharing> VehicleSharings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingAgentMapping> VehicleSharingAgentMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingAgentMapping> VehicleSharingAgentMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingBidding> VehicleSharingBiddings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingDemand> VehicleSharingDemands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingExternalTrip> VehicleSharingExternalTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingExternalTrip> VehicleSharingExternalTrips1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingExternalTrip> VehicleSharingExternalTrips2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingInternalTrip> VehicleSharingInternalTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingInternalTrip> VehicleSharingInternalTrips1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingInternalTrip> VehicleSharingInternalTrips2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingInternalTrip> VehicleSharingInternalTrips3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingInternalTrip> VehicleSharingInternalTrips4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingInternalTripAdjustment> VehicleSharingInternalTripAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleSharingInternalTripAdjustment> VehicleSharingInternalTripAdjustments1 { get; set; }
    }
}
