//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContructualRequisitionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContructualRequisitionDetail()
        {
            this.ContructualRequisitionDetailEntries = new HashSet<ContructualRequisitionDetailEntry>();
        }
    
        public long RowSerial { get; set; }
        public System.Guid PK_ContructualRequisitionDetail { get; set; }
        public System.Guid FK_ContructualRequisition { get; set; }
        public string VehicleTypeLayer1 { get; set; }
        public string VehicleTypeLayer1_english { get; set; }
        public string VehicleTypeLayer1_bangla { get; set; }
        public string VehicleTypeLayer2 { get; set; }
        public string VehicleTypeLayer2_english { get; set; }
        public string VehicleTypeLayer2_bangla { get; set; }
        public string VehicleTypeLayer3 { get; set; }
        public string VehicleTypeLayer3_english { get; set; }
        public string VehicleTypeLayer3_bangla { get; set; }
        public string StartingLocation { get; set; }
        public string FinishingLocation { get; set; }
        public long PricePerVehicle { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ContructualRequisition ContructualRequisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContructualRequisitionDetailEntry> ContructualRequisitionDetailEntries { get; set; }
    }
}
