//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContructualRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContructualRequisition()
        {
            this.ContructualRequisitionDetails = new HashSet<ContructualRequisitionDetail>();
        }
    
        public long RowSerial { get; set; }
        public System.Guid PK_ContructualRequisition { get; set; }
        public System.Guid FK_RequisitionAgent { get; set; }
        public System.Guid FK_ContructualRequisitionCompany { get; set; }
        public System.DateTime ContructAcitivatingDate { get; set; }
        public System.DateTime ContructDeactivatingDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> REF_FK_Depo { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual ContructualRequisitionCompany ContructualRequisitionCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContructualRequisitionDetail> ContructualRequisitionDetails { get; set; }
    }
}
