//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContructualRequisitionDetailEntry
    {
        public long RowSerial { get; set; }
        public System.Guid PK_ContructualRequisitionDetailEntry { get; set; }
        public System.Guid FK_ContructualRequisitionDetail { get; set; }
        public int VehicleCount { get; set; }
        public long PricePerVehicle { get; set; }
        public long FinalContructedPrice { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public Nullable<int> Status { get; set; }
        public System.Guid FK_AppUser_AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedAt { get; set; }
        public Nullable<System.Guid> FK_AppUser_ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual ContructualRequisitionDetail ContructualRequisitionDetail { get; set; }
    }
}
