//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public System.Guid PK_Dealer { get; set; }
        public string DealerCode { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> AssignTime { get; set; }
        public Nullable<System.Guid> FK_Vehicle { get; set; }
    }
}
