//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelConsumptionDemand
    {
        public long PK_FuelConsumptionDemand { get; set; }
        public bool IsDeleted { get; set; }
        public string TrackingID { get; set; }
        public string PRG_Type { get; set; }
        public long FK_FuelPump { get; set; }
        public System.Guid FK_Vehicle { get; set; }
        public Nullable<long> FK_RequisitionTrip { get; set; }
        public Nullable<System.Guid> FK_LocationFrom { get; set; }
        public Nullable<System.Guid> FK_LocationTo { get; set; }
        public System.DateTime RequiredAt { get; set; }
        public string FuelType { get; set; }
        public string FuelUnitType { get; set; }
        public string Status { get; set; }
        public decimal Vehicle_KPL { get; set; }
        public decimal RequiredQuantity_Auto { get; set; }
        public decimal RequiredQuantity_Manual { get; set; }
        public decimal FuelUnitPrice { get; set; }
        public Nullable<decimal> GivenQuantity { get; set; }
        public Nullable<decimal> GivenQuantityPrice { get; set; }
        public Nullable<decimal> ExcessQuantity { get; set; }
        public Nullable<decimal> ExcessQuantityPrice { get; set; }
        public string BusinessUnit_1 { get; set; }
        public Nullable<decimal> BusinessUnit_1_CarringPercentage { get; set; }
        public Nullable<decimal> BusinessUnit_1_GivenQuantityPrice { get; set; }
        public string BusinessUnit_2 { get; set; }
        public Nullable<decimal> BusinessUnit_2_CarringPercentage { get; set; }
        public Nullable<decimal> BusinessUnit_2_GivenQuantityPrice { get; set; }
        public System.Guid FK_AppUser_Client { get; set; }
        public Nullable<System.Guid> FK_AppUser_FuelGivenBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> FuelGivenAt { get; set; }
        public Nullable<bool> OracleDB_IsPushed { get; set; }
        public Nullable<System.DateTime> OracleDB_PushedAt { get; set; }
        public Nullable<bool> OracleDB_IsPulled { get; set; }
        public Nullable<System.DateTime> OracleDB_PulledAt { get; set; }
        public string RequisitionTrip_TrackingID { get; set; }
        public string Taker_Staff_ID { get; set; }
        public string Taker_Staff_Name { get; set; }
        public Nullable<System.Guid> FK_AppUser_ExcessMoneyGivenBy { get; set; }
        public Nullable<System.DateTime> ExcessMoneyGivenAt { get; set; }
        public Nullable<long> FK_Requisition { get; set; }
    
        public virtual FuelPump FuelPump { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
