//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS_DeviceExisting
    {
        public long PK_GPS_DeviceExisting { get; set; }
        public string GpsDeviceModel { get; set; }
        public string GpsIMEINumber { get; set; }
        public string GpsMobileNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.Guid> FK_AppUser_CreatetBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.Guid> FK_AppUser_UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string StatusText { get; set; }
        public Nullable<System.Guid> FK_AppUser_StatusUpdatedBy { get; set; }
        public Nullable<System.DateTime> Status_UpdatedAt { get; set; }
    }
}
