//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndividualRequisition()
        {
            this.IndividualRequisitionBiddings = new HashSet<IndividualRequisitionBidding>();
        }
    
        public long RowSerial { get; set; }
        public System.Guid PK_IndividualRequisition { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> WantedCount { get; set; }
        public System.DateTime PossibleJourneyStartDateTime { get; set; }
        public System.Guid FK_RequisitionAgent { get; set; }
        public Nullable<System.Guid> FK_Depo_From { get; set; }
        public string StartingLocation { get; set; }
        public Nullable<double> StartingLatitude { get; set; }
        public Nullable<double> StartingLongitude { get; set; }
        public Nullable<System.Guid> FK_Depo_To { get; set; }
        public string FinishingLocation { get; set; }
        public Nullable<double> FinishingLatitude { get; set; }
        public Nullable<double> FinishingLongitude { get; set; }
        public string VehicleType { get; set; }
        public string VehicleTypeLayer1 { get; set; }
        public string VehicleTypeLayer1_english { get; set; }
        public string VehicleTypeLayer1_bangla { get; set; }
        public string VehicleTypeLayer2 { get; set; }
        public string VehicleTypeLayer2_english { get; set; }
        public string VehicleTypeLayer2_bangla { get; set; }
        public string VehicleTypeLayer3 { get; set; }
        public string VehicleTypeLayer3_english { get; set; }
        public string VehicleTypeLayer3_bangla { get; set; }
        public string VehicleCapacity { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> IsEndLevelRequisition { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Depo Depo { get; set; }
        public virtual Depo Depo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualRequisitionBidding> IndividualRequisitionBiddings { get; set; }
    }
}
