//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingBayUtilization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoadingBayUtilization()
        {
            this.LoadingBays = new HashSet<LoadingBay>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public long PK_LoadingBayUtilization { get; set; }
        public long FK_LoadingBay { get; set; }
        public Nullable<System.Guid> FK_Vehicle { get; set; }
        public string UseType { get; set; }
        public Nullable<long> FK_ParkingInOut { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public System.Guid FK_AppUser_StartedBy { get; set; }
        public Nullable<System.Guid> FK_AppUser_EndedBy { get; set; }
        public Nullable<long> StayTimeMinute { get; set; }
        public string OWN_MHT_DHT { get; set; }
        public string DeviceId_Started { get; set; }
        public string DeviceId_Ended { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadingBay> LoadingBays { get; set; }
        public virtual LoadingBay LoadingBay { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
