//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoadingBay()
        {
            this.LoadingBayUtilizations = new HashSet<LoadingBayUtilization>();
            this.ParkingInOuts = new HashSet<ParkingInOut>();
        }
    
        public long PK_LoadingBay { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public long FK_LocationBuilding { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> FK_UpdatedByUser { get; set; }
        public Nullable<System.Guid> FK_DeletedByUser { get; set; }
        public Nullable<long> FK_LoadingBayUtilization_Last { get; set; }
        public string CurrentUseType { get; set; }
    
        public virtual LoadingBayUtilization LoadingBayUtilization { get; set; }
        public virtual LocationBuilding LocationBuilding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadingBayUtilization> LoadingBayUtilizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingInOut> ParkingInOuts { get; set; }
    }
}
