//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationWiseGP
    {
        public long PK_LocationWiseGP { get; set; }
        public string PRG_Type { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.Guid FK_Location { get; set; }
        public long GPCount { get; set; }
        public System.Guid FK_AppUser_Creator { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
