//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileRole_MobileMenu
    {
        public long PK_MobileRole_MobileMenu { get; set; }
        public long FK_MobileRole { get; set; }
        public long FK_MobileMenu { get; set; }
        public Nullable<bool> IsAccessible { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual MobileMenu MobileMenu { get; set; }
        public virtual MobileRole MobileRole { get; set; }
    }
}
