//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingInOut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingInOut()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public long PK_ParkingInOut { get; set; }
        public string DevelopersNote { get; set; }
        public System.Guid FK_Vehicle { get; set; }
        public System.Guid FK_Location { get; set; }
        public Nullable<bool> InOrOut { get; set; }
        public System.DateTime In_IssueDateTime { get; set; }
        public System.Guid In_FK_CreatedByUser { get; set; }
        public Nullable<System.DateTime> BayAssign_IssueDateTime { get; set; }
        public Nullable<System.DateTime> BayAssign_CreatedDateTime { get; set; }
        public Nullable<System.Guid> BayAssign_FK_CreatedByUser { get; set; }
        public Nullable<System.DateTime> BayAssign_UpdateDateTime { get; set; }
        public Nullable<System.Guid> BayAssign_FK_UpdatedByUser { get; set; }
        public Nullable<System.DateTime> FactoryIn_IssueDateTime { get; set; }
        public Nullable<System.Guid> FactoryIn_FK_CreatedByUser { get; set; }
        public Nullable<System.DateTime> Out_IssueDateTime { get; set; }
        public Nullable<System.Guid> Out_FK_CreatedByUser { get; set; }
        public string Out_DriverStaffId { get; set; }
        public string Out_Note { get; set; }
        public Nullable<long> FK_RequisitionTrip { get; set; }
        public Nullable<bool> IsBeforeOrAfter { get; set; }
        public Nullable<long> FK_PRG_Type { get; set; }
        public string BayAssign_BayName { get; set; }
        public Nullable<long> BayAssign_FK_LocationDepartment { get; set; }
        public string In_LoadOrEmpty { get; set; }
        public Nullable<System.DateTime> FactoryOut_IssueDateTime { get; set; }
        public Nullable<System.Guid> FactoryOut_FK_CreatedByUser { get; set; }
        public string BayAssign_WareHouseName { get; set; }
        public Nullable<long> FK_Requisition { get; set; }
        public Nullable<long> BayAssign_FK_LocationBuilding { get; set; }
        public Nullable<long> BayAssign_FK_LoadingBay { get; set; }
        public Nullable<long> FK_LoadingBayUtilization { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual LoadingBay LoadingBay { get; set; }
        public virtual Location Location { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
