//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRG_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRG_Type()
        {
            this.TemporaryVehicles = new HashSet<TemporaryVehicle>();
            this.VehicleInOutManuals = new HashSet<VehicleInOutManual>();
        }
    
        public long PK_PRG_Type { get; set; }
        public string Title { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Show_VehicleGateInOutManual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemporaryVehicle> TemporaryVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleInOutManual> VehicleInOutManuals { get; set; }
    }
}
