//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadyReport
    {
        public long PK_RadyReport { get; set; }
        public string BaseModule { get; set; }
        public string ReportName { get; set; }
        public string PRG_Type { get; set; }
        public string Key { get; set; }
        public string Key_nvarchar { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public string Value_varchar { get; set; }
    }
}
