//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingRequest
    {
        public long PK_ReceivingRequest { get; set; }
        public string TrackingID { get; set; }
        public System.Guid FK_AppUser_Client { get; set; }
        public long FK_LocationDepartment { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime AssumedGateReceivingDateTime { get; set; }
        public string CarrerType { get; set; }
        public string Status { get; set; }
        public string Note_Creation { get; set; }
        public Nullable<System.Guid> FK_AppUser_ReceivingGate { get; set; }
        public Nullable<System.DateTime> GateReceivingDateTime { get; set; }
        public Nullable<System.Guid> FK_AppUser_FinalReceiver { get; set; }
        public Nullable<System.DateTime> FinalReceivingDateTime { get; set; }
        public string Item1_Name { get; set; }
        public string Item1_Note_Creation { get; set; }
        public string Item1_GateReceivingDoccumentNumber { get; set; }
        public string Item1_Note_FinalReceival { get; set; }
        public string Item1_FinalReceival_StaffId { get; set; }
        public string Item1_FinalReceival_StaffName { get; set; }
        public string Item1_Status { get; set; }
        public string Item2_Name { get; set; }
        public string Item2_Note_Creation { get; set; }
        public string Item2_GateReceivingDoccumentNumber { get; set; }
        public string Item2_Note_FinalReceival { get; set; }
        public string Item2_FinalReceival_StaffId { get; set; }
        public string Item2_FinalReceival_StaffName { get; set; }
        public string Item2_Status { get; set; }
        public string Item3_Name { get; set; }
        public string Item3_Note_Creation { get; set; }
        public string Item3_GateReceivingDoccumentNumber { get; set; }
        public string Item3_Note_FinalReceival { get; set; }
        public string Item3_FinalReceival_StaffId { get; set; }
        public string Item3_FinalReceival_StaffName { get; set; }
        public string Item3_Status { get; set; }
        public string Item4_Name { get; set; }
        public string Item4_Note_Creation { get; set; }
        public string Item4_GateReceivingDoccumentNumber { get; set; }
        public string Item4_Note_FinalReceival { get; set; }
        public string Item4_FinalReceival_StaffId { get; set; }
        public string Item4_FinalReceival_StaffName { get; set; }
        public string Item4_Status { get; set; }
        public string Item5_Name { get; set; }
        public string Item5_Note_Creation { get; set; }
        public string Item5_GateReceivingDoccumentNumber { get; set; }
        public string Item5_Note_FinalReceival { get; set; }
        public string Item5_FinalReceival_StaffId { get; set; }
        public string Item5_FinalReceival_StaffName { get; set; }
        public string Item5_Status { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual AppUser AppUser2 { get; set; }
        public virtual LocationDepartment LocationDepartment { get; set; }
    }
}
