//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.RequisitionTrip_Finished = new HashSet<RequisitionTrip_Finished>();
            this.RequisitionTrips = new HashSet<RequisitionTrip>();
        }
    
        public long PK_Requisition { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string TrackingID { get; set; }
        public Nullable<System.Guid> FK_Location_From { get; set; }
        public string StartingLocation { get; set; }
        public Nullable<System.Guid> FK_Location_To { get; set; }
        public string FinishingLocation { get; set; }
        public System.DateTime PossibleJourneyStartDateTime { get; set; }
        public Nullable<int> FK_RequisitionVehicleType { get; set; }
        public Nullable<long> FK_RequisitionBusinessUnit { get; set; }
        public Nullable<long> FK_RequisitionProductType { get; set; }
        public Nullable<double> WantedCount { get; set; }
        public string LCNumber { get; set; }
        public string DeliveryType { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> JobNo { get; set; }
        public string UnitNo { get; set; }
        public Nullable<decimal> WeightInKG { get; set; }
        public string ClientNote { get; set; }
        public string StatusText { get; set; }
        public System.Guid FK_AppUser_Client { get; set; }
        public string PRG_Type { get; set; }
        public Nullable<System.Guid> FK_ReferenceDepo { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.Guid> FK_AppUser_Verifier { get; set; }
        public Nullable<System.DateTime> VerifiedAt { get; set; }
        public Nullable<double> AcceptedCount { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<long> FK_LocationDepartment_From { get; set; }
        public Nullable<long> FK_LocationDepartment_To { get; set; }
        public string AttachedFile1_Path { get; set; }
        public string AttachedFile2_Path { get; set; }
        public string AttachedFile3_Path { get; set; }
        public string AttachedFile4_Path { get; set; }
        public Nullable<bool> MailSend { get; set; }
        public string MailReceiverGroup { get; set; }
        public Nullable<System.DateTime> MailSentAt { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual LocationDepartment LocationDepartment { get; set; }
        public virtual LocationDepartment LocationDepartment1 { get; set; }
        public virtual RequisitionBusinessUnit RequisitionBusinessUnit { get; set; }
        public virtual RequisitionProductType RequisitionProductType { get; set; }
        public virtual RequisitionVehicleType RequisitionVehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionTrip_Finished> RequisitionTrip_Finished { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionTrip> RequisitionTrips { get; set; }
    }
}
