//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFID_Entry
    {
        public long ID { get; set; }
        public string TotalText_Raw { get; set; }
        public string DistText_Raw { get; set; }
        public Nullable<int> FK_Dist_ID { get; set; }
        public string DistText_Auto { get; set; }
        public string DistText_Manual { get; set; }
        public string DistText_API { get; set; }
        public string LetterText_Raw { get; set; }
        public Nullable<int> FK_Letter_ID { get; set; }
        public string LetterText_Auto { get; set; }
        public string LetterText_Manual { get; set; }
        public string LetterText_API { get; set; }
        public string LastText_Raw { get; set; }
        public string LastText_Manual { get; set; }
        public string TotalText_API { get; set; }
        public string TotalTextMutiple_API { get; set; }
        public Nullable<System.DateTime> LastEntryAt { get; set; }
        public Nullable<int> Status { get; set; }
        public string GateInID { get; set; }
        public Nullable<System.DateTime> GateInDateTime { get; set; }
        public string GateOutID { get; set; }
        public Nullable<System.DateTime> GateOutDateTime { get; set; }
    }
}
