//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFLOrganization
    {
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        public string LocationName { get; set; }
        public Nullable<System.Guid> FK_Location { get; set; }
        public long PK_RFLOrganization { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
