//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestRfidData
    {
        public long PK_TestRfidData { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<bool> InOrOut { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string DevelopersNote { get; set; }
    }
}
