//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportAgency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportAgency()
        {
            this.InstantRequisitions = new HashSet<InstantRequisition>();
            this.RequisitionTrips = new HashSet<RequisitionTrip>();
            this.RequisitionTrip_Finished = new HashSet<RequisitionTrip_Finished>();
        }
    
        public long PK_TransportAgency { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public string DistrictName { get; set; }
        public string Address { get; set; }
        public Nullable<long> DepositeAmount { get; set; }
        public string TradeLicense { get; set; }
        public string MobileNumber_Primary { get; set; }
        public string MobileNumber_Secondary { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<System.Guid> FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> FK_UpdatedByUser { get; set; }
        public Nullable<System.Guid> FK_DeletedByUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantRequisition> InstantRequisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionTrip> RequisitionTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionTrip_Finished> RequisitionTrip_Finished { get; set; }
    }
}
