//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSharingExternalTrip
    {
        public long PK_VehicleSharingExternalTrip { get; set; }
        public long FK_VehicleSharingBidding { get; set; }
        public Nullable<System.Guid> FK_Vehicle { get; set; }
        public Nullable<System.Guid> FK_AppUser_Assigner { get; set; }
        public string MHT_DHT_DriverName { get; set; }
        public string MHT_DHT_DriverContactNumber { get; set; }
        public string MHT_DHT_DriverLiceneseNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsTest { get; set; }
        public string TripNote { get; set; }
        public Nullable<System.DateTime> AssingedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> PrintCopy { get; set; }
        public string StatusText { get; set; }
        public string PaymentStatusText { get; set; }
        public Nullable<System.DateTime> EnteredStartingLocationDateTime { get; set; }
        public Nullable<System.DateTime> LeftStartingLoactionDateTime { get; set; }
        public Nullable<System.DateTime> EnteredFinishingLocationDateTime { get; set; }
        public Nullable<System.DateTime> LeftFinishingLocationDateTime { get; set; }
        public Nullable<System.DateTime> BillApprovedAt { get; set; }
        public Nullable<System.Guid> FK_AppUser_BillApprover { get; set; }
        public Nullable<System.DateTime> BillPaidAt { get; set; }
        public Nullable<System.Guid> FK_AppUser_BillPaidBy { get; set; }
        public string BillingNote { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual AppUser AppUser2 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual VehicleSharingBidding VehicleSharingBidding { get; set; }
    }
}
