//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSharingDemand
    {
        public long PK_VehicleSharingDemand { get; set; }
        public string TrackingID { get; set; }
        public Nullable<long> FK_VehicleSharing { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsTest { get; set; }
        public Nullable<bool> LoadedOrEmpty { get; set; }
        public Nullable<double> WantedCount { get; set; }
        public System.DateTime PossibleJourneyStartDateTime { get; set; }
        public Nullable<double> AcceptedCount { get; set; }
        public System.Guid FK_AppUser_Client { get; set; }
        public Nullable<System.Guid> FK_ReferenceDepo { get; set; }
        public Nullable<System.Guid> FK_AppUser_Approver { get; set; }
        public Nullable<System.Guid> FK_Depo_From { get; set; }
        public string StartingLocation { get; set; }
        public Nullable<System.Guid> FK_Depo_To { get; set; }
        public string FinishingLocation { get; set; }
        public Nullable<double> DistanceGoogle { get; set; }
        public Nullable<double> DistanceRouteChart { get; set; }
        public int FK_RequisitionVehicleType { get; set; }
        public string VehicleType { get; set; }
        public string VehicleTypeLayer1 { get; set; }
        public string VehicleTypeLayer1_english { get; set; }
        public string VehicleTypeLayer1_bangla { get; set; }
        public string VehicleTypeLayer2 { get; set; }
        public string VehicleTypeLayer2_english { get; set; }
        public string VehicleTypeLayer2_bangla { get; set; }
        public string VehicleTypeLayer3 { get; set; }
        public string VehicleTypeLayer3_english { get; set; }
        public string VehicleTypeLayer3_bangla { get; set; }
        public string VehicleCapacity { get; set; }
        public string ClientNote { get; set; }
        public string ApproverNote { get; set; }
        public Nullable<bool> IsHeadDemand { get; set; }
        public Nullable<bool> IsTailDemand { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> VerifiedAt { get; set; }
        public Nullable<System.DateTime> SharedAt { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Depo Depo { get; set; }
        public virtual Depo Depo1 { get; set; }
        public virtual RequisitionVehicleType RequisitionVehicleType { get; set; }
        public virtual VehicleSharing VehicleSharing { get; set; }
    }
}
