//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleWeightTransection
    {
        public long PkVehicleWeightTransection { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> FkCompany { get; set; }
        public string FirstWeightType { get; set; }
        public Nullable<int> FkMaterial_First { get; set; }
        public Nullable<int> FkBridgingScaleMeter_First { get; set; }
        public string FkUserEntity_First { get; set; }
        public Nullable<int> Weight_First { get; set; }
        public string DriverName_First { get; set; }
        public string HelperName_First { get; set; }
        public string DeviceId_First { get; set; }
        public Nullable<System.DateTime> EntryDatetime_First { get; set; }
        public Nullable<int> FkBridgingScaleMeter_Second { get; set; }
        public string FkUserEntity_Second { get; set; }
        public Nullable<int> Weight_Second { get; set; }
        public string DriverName_Second { get; set; }
        public string HelperName_Second { get; set; }
        public string DeviceId_Second { get; set; }
        public Nullable<System.DateTime> EntryDatetime_Second { get; set; }
        public Nullable<int> WeightDifferenece { get; set; }
    }
}
