//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSharingInternalTripAdjustment
    {
        public long PK_VehicleSharingInternalTripAdjustment { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> BillAdjustmentCreatedAt { get; set; }
        public Nullable<System.Guid> FK_AppUser_BillAdjustmentCreator { get; set; }
        public Nullable<System.DateTime> BillAdjustmentPaidAt { get; set; }
        public Nullable<System.Guid> FK_AppUser_BillAdjustmentPaidBy { get; set; }
        public Nullable<double> Distance_Empty2 { get; set; }
        public Nullable<double> Distance_Loaded2 { get; set; }
        public Nullable<double> Distance_Loaded_Plastic2 { get; set; }
        public Nullable<double> Distance_InterCity2 { get; set; }
        public Nullable<double> Distance_InterCHT2 { get; set; }
        public Nullable<double> Distance_Hill2 { get; set; }
        public Nullable<double> Distance_OnlyMover2 { get; set; }
        public Nullable<double> Distance_Loaded_8_To_12_Tons2 { get; set; }
        public Nullable<double> Distance_Loaded_12_To_25_Tons2 { get; set; }
        public Nullable<double> FuelConsumedLitre2 { get; set; }
        public Nullable<double> FuelPricePerLitre2 { get; set; }
        public Nullable<decimal> FuelExpence2 { get; set; }
        public Nullable<bool> FuelExpenceGivenCashOrOil2 { get; set; }
        public Nullable<decimal> BridgeTollFerryCharge2 { get; set; }
        public Nullable<decimal> EntertainmentCCharge2 { get; set; }
        public Nullable<decimal> ParkingCharge2 { get; set; }
        public Nullable<decimal> EntertainmentACharge2 { get; set; }
        public Nullable<decimal> RepairCharge2 { get; set; }
        public Nullable<decimal> OverStayCharge2 { get; set; }
        public Nullable<decimal> OpenBodyCharge2 { get; set; }
        public Nullable<decimal> DemurrageCharge2 { get; set; }
        public Nullable<decimal> TotalExpense2 { get; set; }
        public string AdjustmentNote2 { get; set; }
        public Nullable<double> Distance_Empty3 { get; set; }
        public Nullable<double> Distance_Loaded3 { get; set; }
        public Nullable<double> Distance_Loaded_Plastic3 { get; set; }
        public Nullable<double> Distance_InterCity3 { get; set; }
        public Nullable<double> Distance_InterCHT3 { get; set; }
        public Nullable<double> Distance_Hill3 { get; set; }
        public Nullable<double> Distance_OnlyMover3 { get; set; }
        public Nullable<double> Distance_Loaded_8_To_12_Tons3 { get; set; }
        public Nullable<double> Distance_Loaded_12_To_25_Tons3 { get; set; }
        public Nullable<double> FuelConsumedLitre3 { get; set; }
        public Nullable<double> FuelPricePerLitre3 { get; set; }
        public Nullable<decimal> FuelExpence3 { get; set; }
        public Nullable<bool> FuelExpenceGivenCashOrOil3 { get; set; }
        public Nullable<decimal> BridgeTollFerryCharge3 { get; set; }
        public Nullable<decimal> EntertainmentCCharge3 { get; set; }
        public Nullable<decimal> ParkingCharge3 { get; set; }
        public Nullable<decimal> EntertainmentACharge3 { get; set; }
        public Nullable<decimal> RepairCharge3 { get; set; }
        public Nullable<decimal> OverStayCharge3 { get; set; }
        public Nullable<decimal> OpenBodyCharge3 { get; set; }
        public Nullable<decimal> DemurrageCharge3 { get; set; }
        public Nullable<decimal> TotalExpense3 { get; set; }
        public string AdjustmentNote3 { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual VehicleSharingInternalTrip VehicleSharingInternalTrip { get; set; }
    }
}
