//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInOutManualTypesOfProduct
    {
        public long PK_VehicleInOutManualTypesOfProduct { get; set; }
        public string TitleBangla { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
