//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_StayReportDaily
    {
        public string Vehicle_ { get; set; }
        public string V_Type { get; set; }
        public string Group { get; set; }
        public string Location { get; set; }
        public string User_Depot { get; set; }
        public string In_Gate { get; set; }
        public System.DateTime In_Time { get; set; }
        public string In_Status { get; set; }
        public string Out_Gate { get; set; }
        public Nullable<System.DateTime> Out_Time { get; set; }
        public string Out_Status { get; set; }
        public Nullable<long> Stay_Time__mm_ { get; set; }
        public Nullable<decimal> Stay_Time__hh_mm_ { get; set; }
        public string L_Type { get; set; }
    }
}
