//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTS_InactiveLog
    {
        public long PK_VTS_InactiveLog { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.Guid FK_Vehicle { get; set; }
        public string SimNumber { get; set; }
        public System.DateTime ReportTime { get; set; }
        public System.DateTime LastConnectedTime { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
