//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTS_T366_DataModel
    {
        public long PK_VTS_T366_DataModel { get; set; }
        public string DataIdentifier { get; set; }
        public string DataLength___ { get; set; }
        public string IMEI____ { get; set; }
        public string CommandType__ { get; set; }
        public string EventCode___ { get; set; }
        public string Latitude___ { get; set; }
        public string Longitude___ { get; set; }
        public string DeviceDateTime__ { get; set; }
        public string PositioningStatus_ { get; set; }
        public string NumberOfSatellites_ { get; set; }
        public string GSMSignalStrength_ { get; set; }
        public string Speed_KM___ { get; set; }
        public string Direction_Degree_ { get; set; }
        public string HDOP____ { get; set; }
        public string Altitude_Meter__ { get; set; }
        public string Mileage_Meter__ { get; set; }
        public string RunTime_Second__ { get; set; }
        public string BaseStationInfo_ { get; set; }
        public string IOPortStatus__ { get; set; }
        public string AnalogInputValue_ { get; set; }
        public string AssistedEventInfo_ { get; set; }
        public string CustomizedData__ { get; set; }
        public string ProtocolVersion_ { get; set; }
        public string FuelPercentage__ { get; set; }
        public string TemperatureSensorNoAndValue___ { get; set; }
        public string MaxAccelerationValue_ { get; set; }
        public string MaxDecelerationValue_ { get; set; }
        public string Checksum_____ { get; set; }
    }
}
