//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ParkingInOut
    {
        public int stat { get; set; }
        public long PK_ParkingInOut { get; set; }
        public string InOutStatus { get; set; }
        public string In_LoadOrEmpty { get; set; }
        public string PRG_Type { get; set; }
        public Nullable<System.Guid> FK_Location { get; set; }
        public string ParkingLocation_Name { get; set; }
        public System.Guid In_FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> Out_FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> FactoryIn_FK_CreatedByUser { get; set; }
        public Nullable<System.Guid> FactoryOut_FK_CreatedByUser { get; set; }
        public string ParkingGateIn { get; set; }
        public System.DateTime In_IssueDateTime { get; set; }
        public string ParkingGateOut { get; set; }
        public Nullable<System.DateTime> Out_IssueDateTime { get; set; }
        public string FactoryGateIn { get; set; }
        public Nullable<System.DateTime> FactoryIn_IssueDateTime { get; set; }
        public string FactoryGateOut { get; set; }
        public Nullable<System.DateTime> FactoryOut_IssueDateTime { get; set; }
        public string RegistrationNumber { get; set; }
        public string OWN_MHT_DHT { get; set; }
        public System.Guid FK_Depo { get; set; }
        public string ContactNumber { get; set; }
        public string DepoName { get; set; }
        public Nullable<System.DateTime> BayAssign_IssueDateTime { get; set; }
        public Nullable<long> FK_LoadingBayUtilization { get; set; }
        public string BayAssigner { get; set; }
        public Nullable<long> BayAssign_FK_LocationDepartment { get; set; }
        public string BayAssign_DepartmentCode { get; set; }
        public Nullable<long> BayAssign_FK_LoadingBay { get; set; }
        public string BayAssign_LoadingBay { get; set; }
        public Nullable<long> BayAssign_FK_LocationBuilding { get; set; }
        public string BayAssign_LocationBuilding { get; set; }
    }
}
