//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Requisition
    {
        public long PK_Requisition { get; set; }
        public string TrackingID { get; set; }
        public string PRG_Type { get; set; }
        public string StartingLocation { get; set; }
        public string FinishingLocation { get; set; }
        public System.DateTime PossibleJourneyStartDateTime { get; set; }
        public string LCNumber { get; set; }
        public Nullable<int> JobNo { get; set; }
        public string UnitNo { get; set; }
        public Nullable<decimal> WeightInKG { get; set; }
        public string ClientNote { get; set; }
        public Nullable<double> WantedCount { get; set; }
        public Nullable<double> AcceptedCount { get; set; }
        public System.Guid FK_AppUser_Client { get; set; }
        public Nullable<System.Guid> FK_Location_From { get; set; }
        public Nullable<System.Guid> FK_Location_To { get; set; }
        public Nullable<int> AssignedCount { get; set; }
        public string StatusText { get; set; }
        public string AppUser_Client_FullName { get; set; }
        public string AppUser_Client_ContactNumber { get; set; }
        public string Depo_Client_Name { get; set; }
        public string RequisitionVehicleType_Title_English { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        public string DeliveryType { get; set; }
        public string ProductType { get; set; }
        public string Location_From_Name { get; set; }
        public string Location_From_SiteCode { get; set; }
        public string Location_To_Name { get; set; }
        public string Location_To_SiteCode { get; set; }
        public string Department_From_Code { get; set; }
        public string Department_From_Name { get; set; }
        public string Department_To_Code { get; set; }
        public string Department_To_Name { get; set; }
        public string LastColumn { get; set; }
    }
}
