//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RequisitionTrip
    {
        public string IsNew { get; set; }
        public long PK_RequisitionTrip { get; set; }
        public string TrackingID { get; set; }
        public string PRG_Type { get; set; }
        public string StartingLocation { get; set; }
        public string FinishingLocation { get; set; }
        public System.DateTime PossibleJourneyStartDateTime { get; set; }
        public string LCNumber { get; set; }
        public Nullable<int> JobNo { get; set; }
        public string UnitNo { get; set; }
        public Nullable<decimal> WeightInKG { get; set; }
        public string ClientNote { get; set; }
        public Nullable<double> Requisition_WantedCount { get; set; }
        public Nullable<double> AcceptedCount { get; set; }
        public System.Guid FK_AppUser_Client { get; set; }
        public Nullable<System.Guid> FK_Location_From { get; set; }
        public Nullable<System.Guid> FK_Location_To { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        public string DeliveryType { get; set; }
        public string ProductType { get; set; }
        public string Requisition_StatusText { get; set; }
        public string AppUser_Client_UniqueIDNumber { get; set; }
        public string AppUser_Client_FullName { get; set; }
        public string AppUser_Client_ContactNumber { get; set; }
        public string Depo_Client_Name { get; set; }
        public string RequisitionVehicleType_Title_English { get; set; }
        public string Location_From_Name { get; set; }
        public string Location_From_SiteCode { get; set; }
        public string Location_From_LocationType { get; set; }
        public string Location_To_Name { get; set; }
        public string Location_To_SiteCode { get; set; }
        public string Location_To_LocationType { get; set; }
        public string Department_From_Code { get; set; }
        public string Department_From_Name { get; set; }
        public string Department_To_Code { get; set; }
        public string Department_To_Name { get; set; }
        public Nullable<bool> IsForwarded { get; set; }
        public string PRG_Type_ForwaredTo { get; set; }
        public Nullable<System.Guid> FK_Location_ForwardedTo { get; set; }
        public string OracleDB_GPNumber { get; set; }
        public Nullable<double> Trip_WantedCount { get; set; }
        public Nullable<System.DateTime> FinalWantedAtDateTime { get; set; }
        public string Driver_Staff_ID { get; set; }
        public string Driver_Name { get; set; }
        public string Driver_ContactNumber { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public string AssigningNote { get; set; }
        public string Trip_StatusText { get; set; }
        public Nullable<System.DateTime> TentativeFinishingDateTime { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> FinishedAt { get; set; }
        public Nullable<System.Guid> FK_Vehicle { get; set; }
        public string OWN_MHT_DHT { get; set; }
        public string Trip_PRG_Type { get; set; }
        public string TravelTime { get; set; }
        public string RegistrationNumber { get; set; }
        public string VehicleType { get; set; }
        public Nullable<double> CapacityTon { get; set; }
        public string VehicleDepo_Name { get; set; }
        public string VehicleBrand_Name { get; set; }
        public string VehicleModel_Title { get; set; }
        public string TransportAgency_Name { get; set; }
        public string AppUser_Assigner_UniqueIDNumber { get; set; }
        public string AppUser_Assigner_FullName { get; set; }
        public string AppUser_Assigner_ContactNumber { get; set; }
        public string LastColumn { get; set; }
    }
}
