//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RequisitionTripCustomReport
    {
        public string PRG_Type { get; set; }
        public string Tranjction_ID { get; set; }
        public string GP_Number { get; set; }
        public Nullable<System.DateTime> FinalWantedAt { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Vehicle_s_type_ { get; set; }
        public string Vehicle_number { get; set; }
        public Nullable<long> Hire_amount { get; set; }
        public string Vehicle_User_Group { get; set; }
    }
}
