//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3rdEyE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VehicleInOutManual
    {
        public long PK_VehicleInOutManual { get; set; }
        public string RegistrationNumber { get; set; }
        public string Vehicle_OWN_MHT_DHT { get; set; }
        public string Location_Name { get; set; }
        public string Depo_PRG_Type { get; set; }
        public string Depo_Name { get; set; }
        public string Depo_Category { get; set; }
        public string Destination { get; set; }
        public string InGate_PRG_Type { get; set; }
        public string InGate_FullName { get; set; }
        public System.Guid FK_Location { get; set; }
        public System.DateTime In_IssueDateTime { get; set; }
        public string In_LoadOrEmpty { get; set; }
        public Nullable<bool> In_IsScannedEntry { get; set; }
        public long InReason_PK_VehicleInOutManualReason { get; set; }
        public string InReason_TitleBangla { get; set; }
        public string OutGate_FullName { get; set; }
        public Nullable<System.DateTime> Out_IssueDateTime { get; set; }
        public string Out_LoadOrEmpty { get; set; }
        public Nullable<bool> Out_IsScannedEntry { get; set; }
        public Nullable<long> OutReason_PK_VehicleInOutManualReason { get; set; }
        public string OutReason_TitleBangla { get; set; }
        public Nullable<long> InStayTimeMinute { get; set; }
        public Nullable<long> OutStayTimeMinute { get; set; }
        public int EndignCoulmn { get; set; }
    }
}
